# name: Deploy to AWS

# on:
#   push:
#     branches:
#       - dev

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   terraform:
#     name: Terraform Apply
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.5.0

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v3
#         with:
#           role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_IAM_ROLE }}
#           role-session-name: GitHubActionsDeployment
#           aws-region: ap-northeast-1

#       - name: Initialize Terraform
#         run: terraform init

#       - name: Validate Terraform
#         run: terraform validate

#       - name: Plan Terraform
#         run: terraform plan -out=tfplan

#       - name: Apply Terraform
#         run: terraform apply -auto-approve tfplan
